package com.classwright.runtime;

import com.classwright.ClasswrightException;

import java.lang.invoke.MethodHandles.Lookup;

/**
 * How generated bytes become a loaded class.
 *
 * <p>Three implementations, and the choice between them is the single most consequential decision
 * this library makes about memory. They trade off against each other:
 *
 * <table border="1">
 *   <caption>Strategy comparison</caption>
 *   <tr><th></th><th>{@link Hidden}</th><th>{@link Named}</th><th>{@link ChildLoader}</th></tr>
 *   <tr><td>Unloadable</td><td>yes, individually</td><td><strong>never</strong></td>
 *       <td>yes, per loader</td></tr>
 *   <tr><td>{@code Class.forName}</td><td>no</td><td>yes</td><td>yes</td></tr>
 *   <tr><td>Package-private override</td><td>yes</td><td>yes</td><td>no</td></tr>
 *   <tr><td>Extra class loader</td><td>no</td><td>no</td><td>one per scope</td></tr>
 *   <tr><td>Needs an open package</td><td>yes</td><td>yes</td><td>no</td></tr>
 * </table>
 *
 * <p>{@link Hidden} is the default, and the reason is measured rather than assumed: over 20 000
 * generated classes it reclaims 100% and returns metaspace to baseline, where {@link Named}
 * reclaims 0% and retains 24 MB permanently. That second figure is CGLib's production failure
 * reproduced exactly. See {@code docs/RESEARCH.md} §2.
 *
 * <p>{@link Named} remains available because some tooling genuinely needs a class it can look up by
 * name, and refusing that would just push people back to a library that leaks. The cost is
 * documented rather than hidden.
 */
public interface DefinitionStrategy {

    /**
     * A short name for diagnostics.
     *
     * @return a short name, for diagnostics
     */
    String name();

    /**
     * What makes this strategy <em>semantically distinct</em> for generation caching.
     *
     * <p>A cache that keyed on {@link #name()} alone treated every {@code ChildLoader} — whatever
     * parent it delegates to — as the same configuration, and served the class defined for one
     * parent to requests for another. Stateless strategies can keep the default; a strategy with
     * configuration (a chosen parent loader, say) must return something identity- or
     * value-distinct per configuration. Cache keys may hold the returned object weakly, so its
     * lifetime need not worry the implementor.
     *
     * @return a value equal (or identical) exactly when two strategy instances define classes
     *         the same way
     */
    default Object cacheIdentity() {
        return name();
    }

    /**
     * Whether classes defined this way can be collected while their defining loader stays alive.
     *
     * <p>The property that decides whether a long-running application's metaspace grows without
     * bound.
     *
     * @return whether classes defined this way can be collected while their loader stays alive
     */
    boolean producesUnloadableClasses();

    /**
     * Whether {@code Class.forName} can resolve classes defined this way.
     *
     * @return whether {@code Class.forName} can resolve classes defined this way
     */
    boolean producesResolvableNames();

    /**
     * Whether this strategy can be used at the given site.
     *
     * @param site the intended package and loader
     * @return whether {@link #define} would succeed
     */
    boolean isUsableAt(DefinitionSite site);

    /**
     * Defines the class.
     *
     * @param site       where it should live
     * @param classBytes a complete class file
     * @return the loaded class
     * @throws ClasswrightException if definition fails
     */
    DefinedClass define(DefinitionSite site, byte[] classBytes);

    /**
     * The default: unloadable hidden classes in the target's own package.
     *
     * @return the hidden-class strategy
     */
    static DefinitionStrategy hidden() {
        return Hidden.NESTMATE;
    }

    /**
     * Ordinary named classes. Resolvable by name, never unloaded.
     *
     * @return the named-class strategy
     */
    static DefinitionStrategy named() {
        return Named.INSTANCE;
    }

    /**
     * A throwaway child loader. The fallback when the target's package is closed.
     *
     * @return the child-loader strategy that decides its parent per definition site
     */
    static DefinitionStrategy childLoader() {
        // The site-decided form is stateless — its cache identity is a shared string and its
        // loader is chosen per definition — so every caller can share one instance. This sits on
        // ClassDefiner.alongside's fallback path, which should not allocate per call.
        return ChildLoader.SITE_DECIDED;
    }

    // ==========================================================================================

    /**
     * Defines an unloadable hidden class in the target's package and loader.
     *
     * <p>A hidden class is not entered in its loader's class table. Nothing can find it by name, and
     * crucially nothing <em>holds</em> it by name either, so it becomes collectible as soon as it is
     * unreachable &mdash; independently of the loader, which normally keeps every class it defined
     * alive forever.
     *
     * <p>Being defined into the target's own package and loader means the generated class shares a
     * runtime package with its superclass, so it can override package-private methods. With
     * {@code NESTMATE} it also joins the target's nest and can reach private members.
     *
     * <p>Two consequences callers must know about. The class name gains a
     * {@code /0x...} suffix and is not a valid binary name, so {@code Class.forName} on it fails
     * by design. And instances can only be created through the returned {@link Lookup}, because no
     * other class's bytecode can name it in a {@code new} instruction.
     */
    final class Hidden implements DefinitionStrategy {

        /** Joins the target's nest, gaining access to its private members. */
        static final Hidden NESTMATE = new Hidden(true);

        /** Stays outside the nest. Package-private access only. */
        static final Hidden PLAIN = new Hidden(false);

        private final boolean nestmate;

        private Hidden(boolean nestmate) {
            this.nestmate = nestmate;
        }

        @Override
        public String name() {
            return nestmate ? "hidden (nestmate)" : "hidden";
        }

        @Override
        public boolean producesUnloadableClasses() {
            return true;
        }

        @Override
        public boolean producesResolvableNames() {
            return false;
        }

        @Override
        public boolean isUsableAt(DefinitionSite site) {
            // Full privilege, not merely package access: see DefinitionSite.canDefineHiddenClass.
            return site.canDefineHiddenClass();
        }

        @Override
        public DefinedClass define(DefinitionSite site, byte[] classBytes) {
            Lookup lookup = site.lookup();
            if (lookup == null || !site.canDefineHiddenClass()) {
                throw new ClasswrightException(site.explainMissingLookup());
            }
            try {
                // initialize=false: the class links now but its static initialiser runs on first
                // use, matching how an ordinary class behaves. Initialising eagerly would make
                // generation slower and would run user code at a surprising moment.
                Lookup defined = nestmate
                        ? lookup.defineHiddenClass(classBytes, false, Lookup.ClassOption.NESTMATE)
                        : lookup.defineHiddenClass(classBytes, false);
                return new DefinedClass(defined.lookupClass(), defined, this);
            } catch (IllegalAccessException | LinkageError e) {
                throw new ClasswrightException("the JVM rejected a generated hidden class in "
                        + site.packageName() + ": " + e, e);
            }
        }
    }

    /**
     * Defines an ordinary, named class in the target's package and loader.
     *
     * <p>Everything works the way people expect: {@code Class.forName} finds it, debuggers show a
     * real name, and frameworks that parse class names are happy.
     *
     * <p><strong>It will never be unloaded.</strong> The class loader records it permanently, so it
     * is retained for as long as the loader lives &mdash; which for an application loader means
     * forever. This is precisely CGLib's leak, and it is offered only because some tooling requires
     * a resolvable name and the alternative is that those users go back to CGLib.
     */
    final class Named implements DefinitionStrategy {

        static final Named INSTANCE = new Named();

        private Named() {
        }

        @Override
        public String name() {
            return "named";
        }

        @Override
        public boolean producesUnloadableClasses() {
            return false;
        }

        @Override
        public boolean producesResolvableNames() {
            return true;
        }

        @Override
        public boolean isUsableAt(DefinitionSite site) {
            return site.hasFullPrivilegeLookup();
        }

        @Override
        public DefinedClass define(DefinitionSite site, byte[] classBytes) {
            Lookup lookup = site.lookup();
            if (lookup == null) {
                throw new ClasswrightException(site.explainMissingLookup());
            }
            try {
                Class<?> type = lookup.defineClass(classBytes);
                return new DefinedClass(type, lookup, this);
            } catch (IllegalAccessException | LinkageError e) {
                throw new ClasswrightException("the JVM rejected a generated class in "
                        + site.packageName() + ": " + e, e);
            }
        }
    }

    /**
     * Defines classes in a fresh child class loader.
     *
     * <p>The fallback for when the target's package is closed to us, which happens with a named
     * module that does not {@code opens} its packages. It needs no lookup and no cooperation from
     * the target at all: the child loader delegates to the target's loader, so the generated class
     * can still extend it and call its public and protected methods.
     *
     * <p>What is lost is the shared runtime package. Two classes are package-mates only if they
     * have the same package name <em>and</em> the same loader, so a class here can never override a
     * package-private method however its package is named.
     *
     * <p>Unloading works, but at loader granularity: everything defined in one instance of this
     * strategy is collected together, once the loader and all its classes are unreachable. That
     * makes it a reasonable fit for a scope that is torn down as a unit, and a poor one for
     * open-ended proxy creation, since each strategy instance is one more loader.
     */
    final class ChildLoader implements DefinitionStrategy {

        /** The shared site-decided instance {@link DefinitionStrategy#childLoader()} returns. */
        private static final ChildLoader SITE_DECIDED = new ChildLoader();

        private final GeneratedClassLoader loader;

        /**
         * Creates a strategy that decides its parent loader per definition, from the site.
         */
        public ChildLoader() {
            this(null);
        }

        /**
         * Creates a strategy whose generated classes load in a child of the given loader.
         *
         * @param parent the loader to delegate to, or {@code null} to decide per definition from
         *               the site
         */
        public ChildLoader(ClassLoader parent) {
            this.loader = parent == null ? null : new GeneratedClassLoader(parent);
        }

        @Override
        public String name() {
            return "child loader";
        }

        @Override
        public Object cacheIdentity() {
            // An explicit parent makes this instance a distinct configuration: the class defined
            // for one parent must not be served to a request for another. The site-decided form
            // is a pure function of the definition site, so the shared name identifies it.
            return loader != null ? loader : "child loader (site-decided)";
        }

        @Override
        public boolean producesUnloadableClasses() {
            return true;
        }

        @Override
        public boolean producesResolvableNames() {
            return true;
        }

        @Override
        public boolean isUsableAt(DefinitionSite site) {
            return true;   // needs nothing from the target
        }

        /**
         * Shared loaders for the parent-chosen-per-site path, one per parent <em>cohort</em>.
         *
         * <p>Without sharing, every definition built a fresh {@code ClassLoader} — a
         * {@code ClassLoaderData} chunk of metaspace each, a longer loader graph for every GC to
         * walk. But unloading happens at loader granularity, so unbounded sharing has the
         * opposite failure: ten thousand classes in one loader, and the single live one keeps
         * the other 9,999 in metaspace. The middle ground is a cohort — a definition slot is
         * reserved at selection, under this map's lock, and once {@link #COHORT_LIMIT} slots are
         * taken the loader is retired and a fresh one started. Reserving at selection rather
         * than counting at definition makes the limit a hard bound even under concurrent
         * definition: one live class pins at most a cohort's worth of neighbours, while loader
         * count stays a small fraction of class count. (A definition that fails after reserving
         * keeps its slot, which can only under-fill a cohort, never overfill one.) A retired
         * loader is dropped from the map and lives exactly as long as its classes do. Safe
         * because generated classes never reference one another (one-class architecture), and
         * this strategy never grants package-private access, so nothing observable depends on
         * which cohort a class landed in.
         *
         * <p>Weak keys and weak values: the map pins neither the parent nor the current cohort,
         * whose lifetime stays governed by its classes.
         */
        private static final java.util.Map<ClassLoader,
                java.lang.ref.WeakReference<GeneratedClassLoader>> SHARED =
                new java.util.WeakHashMap<>();

        /** Classes per shared loader before it is retired; see {@link #SHARED}. */
        private static final int COHORT_LIMIT =
                Math.max(1, Integer.getInteger("classwright.childLoaderCohort", 64));

        private static GeneratedClassLoader sharedFor(ClassLoader parent) {
            if (parent == null) {
                return new GeneratedClassLoader(null);
            }
            synchronized (SHARED) {
                java.lang.ref.WeakReference<GeneratedClassLoader> existing = SHARED.get(parent);
                GeneratedClassLoader shared = existing == null ? null : existing.get();
                if (shared == null || !shared.tryReserve(COHORT_LIMIT)) {
                    shared = new GeneratedClassLoader(parent);
                    shared.tryReserve(COHORT_LIMIT);   // fresh loader, COHORT_LIMIT >= 1: cannot fail
                    SHARED.put(parent, new java.lang.ref.WeakReference<>(shared));
                }
                return shared;
            }
        }

        @Override
        public DefinedClass define(DefinitionSite site, byte[] classBytes) {
            GeneratedClassLoader target = loader != null
                    ? loader
                    : sharedFor(parentFor(site));
            try {
                Class<?> defined = target.define(classBytes);
                // Obtain a lookup on the result so callers get the same capabilities as the other
                // strategies. The class sits in a fresh loader and therefore in the unnamed module,
                // which is open to everyone, so this succeeds even though the *target's* package
                // was closed -- which is why this strategy was chosen in the first place.
                return new DefinedClass(defined, lookupOn(defined), this);
            } catch (LinkageError e) {
                throw new ClasswrightException(
                        "the JVM rejected a generated class in a child loader: " + e, e);
            }
        }

        private static Lookup lookupOn(Class<?> defined) {
            return LookupResolver.tryResolve(defined).orElse(null);
        }

        /**
         * Chooses the loader to delegate to.
         *
         * <p>The site's own loader, except when that is the bootstrap loader. Extending a class
         * from {@code java.*} would otherwise produce a child of bootstrap, which can see neither
         * Classwright's own types nor anything from the application — and generated classes always
         * reference both. Falling back to the loader that loaded Classwright keeps the generated
         * class able to resolve what it needs.
         */
        private static ClassLoader parentFor(DefinitionSite site) {
            ClassLoader siteLoader = site.classLoader();
            ClassLoader fallback = DefinitionStrategy.class.getClassLoader();
            if (siteLoader == null) {
                return fallback;
            }
            // The generated class references Classwright's own types, so its loader must resolve
            // them. The platform loader is the trap: it loads java.sql and friends but cannot see
            // the application classpath, and a child of it would fail to link its own superclass.
            // Classwright's loader sees platform classes through ordinary delegation, so it is
            // the right parent whenever the site's loader cannot see Classwright.
            try {
                if (Class.forName(DefinitionStrategy.class.getName(), false, siteLoader)
                        == DefinitionStrategy.class) {
                    return siteLoader;
                }
            } catch (ClassNotFoundException notVisible) {
                // Fall through.
            }
            return fallback;
        }

        /** Named so that a heap dump or a leak report says what it is. */
        private static final class GeneratedClassLoader extends ClassLoader {

            private final java.util.concurrent.atomic.AtomicInteger reserved =
                    new java.util.concurrent.atomic.AtomicInteger();

            GeneratedClassLoader(ClassLoader parent) {
                super("classwright-generated", parent);
            }

            /**
             * Claims one definition slot, or refuses because the cohort is full. Called only by
             * {@code sharedFor}; explicit-parent loaders are dedicated and have no cohort limit.
             */
            boolean tryReserve(int limit) {
                int claimed;
                do {
                    claimed = reserved.get();
                    if (claimed >= limit) {
                        return false;
                    }
                } while (!reserved.compareAndSet(claimed, claimed + 1));
                return true;
            }

            Class<?> define(byte[] classBytes) {
                // A null name makes the JVM read it from the bytes, so this loader never needs to
                // parse a constant pool -- consistent with the library's no-parser rule.
                return defineClass(null, classBytes, 0, classBytes.length);
            }
        }
    }
}
