/**
 * Turns generated bytes into loaded classes, and decides how long those classes live.
 *
 * <p>Where {@code com.classwright.core} produces a {@code byte[]}, this package hands it to the JVM
 * and manages what happens next: which class loader and package it lands in, whether it can ever be
 * unloaded, how it is cached, and how instances of it are created.
 *
 * <h2>Unloading is the whole point</h2>
 *
 * <p>CGLib's worst production problem was that generated classes were immortal. They were defined
 * into the target's own class loader and pinned by a static cache, so a long-running application
 * that kept building proxies kept consuming metaspace it never got back, and a container that
 * redeployed applications leaked the entire application class loader each time.
 *
 * <p>Classwright defines classes as <em>hidden classes</em> by default. A hidden class is not
 * registered in its loader's class table, so it can be collected independently of that loader
 * &mdash; while still living in the loader's package, with all the access that implies. Measured on
 * 20 000 generated classes: hidden classes reclaim 100% and return metaspace to baseline, the
 * classic approach reclaims 0%. See {@code docs/RESEARCH.md} §2.
 *
 * <p>Because a generated class is strongly reachable from every live instance of it, the cache
 * needs only weak references. A proxy class then lives exactly as long as its instances do, which
 * is the correct lifetime and requires no bookkeeping from anyone.
 *
 * <h2>Public API only, with one quarantined exception</h2>
 *
 * <p>Class definition goes exclusively through {@link java.lang.invoke.MethodHandles.Lookup}. There
 * is no {@code sun.misc.Unsafe}, no reflective call into {@code ClassLoader.defineClass}, and no
 * {@code setAccessible} against JDK internals. Those were what JDK 16's strong encapsulation
 * switched off, and they took CGLib with them.
 *
 * <p>A few optional features genuinely cannot be built on public API. Those live in
 * {@code com.classwright.runtime.unsafe}, are reached only through an interface, and are expected
 * to become unavailable one day. {@link com.classwright.runtime.Capabilities} probes for them at
 * runtime so that their absence degrades a feature rather than the library.
 */
package com.classwright.runtime;
