package com.classwright.testkit;

import java.lang.invoke.MethodHandles;

/**
 * Feeds generated bytes to the JVM and reports whether they survive class loading, linking, and
 * verification.
 *
 * <p><strong>The JVM's own verifier is the oracle.</strong> Classwright deliberately has no
 * class-file parser (see {@code com.classwright} package docs), and we do not want one in the test
 * tree either &mdash; a home-grown checker would only ever agree with our own misunderstandings.
 * The JVM already contains an exhaustive, authoritative implementation of the class-file format,
 * and it is the same implementation that will judge our output in production. So we ask it.
 *
 * <p>Verification does not happen at {@code defineClass} time; it happens when the class is linked.
 * Every method here therefore forces initialisation, which forces linking, which forces
 * verification. A class that "defines fine" but fails to verify is exactly the bug we are hunting,
 * so simply defining it would prove nothing.
 *
 * <h2>Failure output</h2>
 *
 * <p>When bytes are rejected, the assertion message embeds a {@code javap} disassembly of the
 * offending class. A raw {@code VerifyError} names a bytecode offset and nothing else, which is
 * close to useless without the listing beside it. Producing that listing automatically turns a
 * twenty-minute debugging session into a ten-second read.
 *
 * @see Javap
 */
public final class ClassVerifier {

    private ClassVerifier() {
    }

    /**
     * Asserts that the given bytes load, link, and verify.
     *
     * <p>The class is defined in a throwaway child class loader, so it can carry any name and is
     * discarded (and unloaded) once the returned {@code Class} becomes unreachable. Tests therefore
     * do not leak metaspace into one another.
     *
     * @param classBytes a complete class file
     * @return the loaded, initialised class
     * @throws AssertionError if the bytes are rejected at any stage, with a disassembly attached
     */
    public static Class<?> assertVerifies(byte[] classBytes) {
        try {
            return defineAndInitialise(classBytes);
        } catch (Throwable failure) {
            throw new AssertionError(
                    "Expected these bytes to verify, but the JVM rejected them: "
                            + describe(failure) + "\n\n" + Javap.disassembleQuietly(classBytes),
                    failure);
        }
    }

    /**
     * Asserts that the given bytes are rejected, and that the rejection is of the expected kind.
     *
     * <p>Used to prove that this harness actually detects bad bytecode. A verification harness that
     * has never been shown to reject anything is not evidence of anything.
     *
     * @param expected   the expected failure type, e.g. {@code VerifyError.class}
     * @param classBytes a class file that should not be accepted
     * @param <T>        the expected failure type
     * @return the actual throwable, for further assertions on its message
     * @throws AssertionError if the bytes were accepted, or rejected for a different reason
     */
    public static <T extends Throwable> T assertRejects(Class<T> expected, byte[] classBytes) {
        Throwable actual;
        try {
            Class<?> accepted = defineAndInitialise(classBytes);
            throw new AssertionError("Expected " + expected.getSimpleName()
                    + ", but the bytes were accepted and produced " + accepted.getName()
                    + "\n\n" + Javap.disassembleQuietly(classBytes));
        } catch (AssertionError e) {
            throw e;
        } catch (Throwable t) {
            actual = t;
        }
        if (!expected.isInstance(actual)) {
            throw new AssertionError("Expected " + expected.getSimpleName() + " but got "
                    + describe(actual) + "\n\n" + Javap.disassembleQuietly(classBytes), actual);
        }
        return expected.cast(actual);
    }

    /**
     * Asserts that the given bytes verify when defined as a <em>hidden</em> class in the lookup's
     * package.
     *
     * <p>This is the path Classwright actually uses in production, so it is worth exercising
     * directly as well as through the generic child-loader path. Note that the class name inside
     * {@code classBytes} must live in {@code lookup}'s own package, and that the resulting class is
     * not discoverable by name.
     *
     * @param lookup     a full-privilege lookup determining the defining package and loader
     * @param classBytes a complete class file
     * @return the loaded, initialised hidden class
     * @throws AssertionError if the bytes are rejected, with a disassembly attached
     */
    public static Class<?> assertVerifiesAsHidden(MethodHandles.Lookup lookup, byte[] classBytes) {
        try {
            return lookup.defineHiddenClass(classBytes, true).lookupClass();
        } catch (Throwable failure) {
            throw new AssertionError(
                    "Expected these bytes to verify as a hidden class in "
                            + lookup.lookupClass().getPackageName() + ", but: " + describe(failure)
                            + "\n\n" + Javap.disassembleQuietly(classBytes),
                    failure);
        }
    }

    /**
     * Defines the bytes in a fresh loader and initialises the result.
     *
     * <p>{@code defineClass} is given a {@code null} name so the JVM derives it from the bytes
     * themselves. That keeps this harness free of any need to read the constant pool, which would
     * be a class-file parser by another name.
     */
    private static Class<?> defineAndInitialise(byte[] classBytes) throws ClassNotFoundException {
        ThrowawayLoader loader = new ThrowawayLoader();
        Class<?> defined = loader.define(classBytes);
        // Re-loading by name with initialize=true forces link -> verify -> <clinit>.
        return Class.forName(defined.getName(), true, loader);
    }

    private static String describe(Throwable t) {
        String message = t.getMessage();
        return t.getClass().getName() + (message == null ? "" : ": " + message);
    }

    /**
     * A class loader that exists to be thrown away.
     *
     * <p>Its parent is the loader of this test kit, so generated classes can reference application
     * and JDK types normally. Because nothing else ever holds a reference to it, the loader and
     * everything it defined are collectible as soon as the test finishes with them.
     */
    private static final class ThrowawayLoader extends ClassLoader {

        ThrowawayLoader() {
            super("classwright-verify", ClassVerifier.class.getClassLoader());
        }

        Class<?> define(byte[] classBytes) {
            return defineClass(null, classBytes, 0, classBytes.length);
        }
    }
}
