package net.sf.cglib.proxy;

import com.classwright.cglib.CallbackAdapters;
import com.classwright.cglib.Coexistence;

/**
 * A {@code java.lang.reflect.Proxy} look-alike whose proxies are generated subclass-style.
 *
 * <p>Reproduces {@code net.sf.cglib.proxy.Proxy}, delegating to
 * {@link com.classwright.proxy.Proxy}. A checked exception the handler throws that the method did
 * not declare arrives wrapped in {@link UndeclaredThrowableException}, as both CGLib and the JDK
 * wrap it.
 *
 * <p>The class shape — non-final, {@link java.io.Serializable}, a protected {@link #h} field set
 * by a protected constructor — is CGLib's, kept so that code which subclasses {@code Proxy} or
 * reflects over it still compiles and links.
 *
 * <p><strong>Two differences.</strong> In CGLib, generated proxy classes <em>extended</em> this
 * class; Classwright's generated classes do not, so {@code proxy instanceof Proxy} is false for
 * proxies created here, and the protected constructor does not register callbacks for
 * {@code getClass()} the way CGLib's did (there is no generated subclass to register them for).
 * And {@link #getProxyClass} returns a class whose constructors mirror {@code Object}'s — there
 * is no generated {@code (InvocationHandler)} constructor to look up reflectively. Create
 * instances with {@link #newProxyInstance}, or use {@link Enhancer#registerCallbacks} for
 * deferred binding.
 */
public class Proxy implements java.io.Serializable {

    /** CGLib 3.3.0's computed value, verified against the reference artifact. */
    @java.io.Serial
    private static final long serialVersionUID = -1067197779399491045L;

    static {
        Coexistence.check();
    }

    /** The handler, as CGLib exposed it to subclasses. */
    protected InvocationHandler h;

    /**
     * Subclass constructor, matching CGLib's.
     *
     * <p>In CGLib this ran from a generated proxy subclass and registered {@code h} as that
     * class's callbacks; Classwright's proxies are not subclasses of this type, so here it only
     * records the handler for the subclass to use.
     *
     * @param h the handler this proxy dispatches to
     */
    protected Proxy(InvocationHandler h) {
        this.h = h;
    }

    /**
     * Classes this factory produced, marked on the class itself.
     *
     * <p>CGLib's {@code isProxyClass} means "generated by <em>this Proxy factory</em>", not
     * "generated by the library" — an ordinary Enhancer proxy answers {@code false} there, and
     * migrated code branches on that distinction. The native
     * {@code com.classwright.proxy.Proxy.isProxyClass} is deliberately broader, so the facade
     * keeps its own record. A {@link ClassValue} keeps it loader-safe: the mark lives on the
     * generated class and dies with it.
     */
    private static final ClassValue<java.util.concurrent.atomic.AtomicBoolean> FACTORY_MADE =
            new ClassValue<>() {
                @Override
                protected java.util.concurrent.atomic.AtomicBoolean computeValue(Class<?> type) {
                    return new java.util.concurrent.atomic.AtomicBoolean();
                }
            };

    /**
     * Creates a proxy implementing the interfaces, dispatching every call to the handler.
     *
     * @param loader     ignored; placement follows the first interface, as the class comment says
     * @param interfaces the interfaces to implement
     * @param handler    receives every method call
     * @return the proxy
     */
    public static Object newProxyInstance(ClassLoader loader, Class[] interfaces,
                                          InvocationHandler handler) {
        Object proxy = com.classwright.proxy.Proxy.newProxyInstance(loader, interfaces,
                (com.classwright.proxy.InvocationHandler)
                        CallbackAdapters.toClasswright(handler));
        FACTORY_MADE.get(proxy.getClass()).set(true);
        return proxy;
    }

    /**
     * Generates the proxy class without creating an instance.
     *
     * @param loader     ignored; placement follows the first interface
     * @param interfaces the interfaces to implement
     * @return the generated class
     */
    public static Class getProxyClass(ClassLoader loader, Class[] interfaces) {
        Class<?> proxyClass = com.classwright.proxy.Proxy.getProxyClass(loader, interfaces);
        FACTORY_MADE.get(proxyClass).set(true);
        return proxyClass;
    }

    /**
     * Whether a class was generated by this factory — this factory specifically, as in CGLib.
     *
     * <p>An Enhancer-generated proxy answers {@code false}, exactly as it did in CGLib; the
     * broader "is this any Classwright proxy" question is the native
     * {@code com.classwright.proxy.Proxy.isProxyClass}.
     *
     * @param type any class
     * @return whether this factory produced it
     */
    public static boolean isProxyClass(Class type) {
        return type != null && FACTORY_MADE.get(type).get();
    }

    /**
     * The handler a proxy dispatches to.
     *
     * @param proxy a proxy from {@link #newProxyInstance}
     * @return the handler it was created with
     * @throws IllegalArgumentException if the object is not this factory's proxy, with CGLib's
     *                                  exact message
     */
    public static InvocationHandler getInvocationHandler(Object proxy) {
        if (proxy == null || !isProxyClass(proxy.getClass())) {
            throw new IllegalArgumentException("Object is not a proxy");
        }
        return (InvocationHandler) CallbackAdapters.toCglib(
                com.classwright.proxy.Proxy.getInvocationHandler(proxy));
    }
}
