package com.classwright.proxy;

import com.classwright.ClasswrightException;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Generates proxy classes at build time instead of at runtime.
 *
 * <p>The normal path generates a class file and defines it on demand. GraalVM native images make
 * that impossible: the image is compiled under a closed-world assumption, so every class has to
 * exist before the program starts and defining one at runtime is not supported at all. This is why
 * Spring moved away from CGLib for its native story.
 *
 * <p>The fix is to do the same work earlier. Given a list of {@link ProxyBlueprint}s, this writes
 * the generated classes into the build output as ordinary {@code .class} files, plus an index that
 * {@link AotProxies} reads at runtime and the reachability metadata native-image needs. The result
 * is that {@code Enhancer.create(...)} finds a class that is already there and never tries to
 * generate one.
 *
 * <p>Useful outside native images too, simply as a way to move generation off startup: an
 * application that builds thousands of proxies pays for them at build time instead.
 *
 * <h2>What it produces</h2>
 *
 * <pre>
 * &lt;output&gt;/com/example/Service$$CW$1a2b3c4d5e6f7a8b.class  the proxy
 *        /META-INF/classwright/proxies.index                   key -&gt; class name, fingerprint
 *        /META-INF/native-image/com.classwright/classwright/reflect-config.json
 *        /META-INF/native-image/com.classwright/classwright/resource-config.json
 * </pre>
 *
 * <h2>Limits, stated plainly</h2>
 *
 * <ul>
 *   <li>Classes are generated with ordinary names, not as hidden classes, so they are never
 *       unloaded. That is inherent: a class compiled into a native image is part of the image.</li>
 *   <li>The proxy lands in its target's package, which means the output directory contains a
 *       package that also exists in another jar. Fine on the class path; a split package under
 *       JPMS.</li>
 *   <li>A {@link CallbackFilter} has to be instantiable at build time, with a no-argument
 *       constructor, because deciding which callback handles which method requires running it.</li>
 * </ul>
 */
public final class AheadOfTime {

    /** Where the runtime looks for the index. */
    public static final String INDEX_RESOURCE = "META-INF/classwright/proxies.index";

    /**
     * The generated-code runtime ABI version this Classwright writes and accepts.
     *
     * <p>A pre-generated proxy's bytecode calls runtime helpers — {@code ProxySupport},
     * {@code CallbackRegistry}, {@code SuperDispatcher} — whose shape is versioned with the
     * generator, not with the public API. A proxy generated by one Classwright can therefore be
     * <em>loaded</em> by a later one whose helpers no longer match, and without a declared
     * version the failure is a {@code NoSuchMethodError} at first dispatch, far from its cause.
     * The index declares the ABI it was generated for ({@code %abi} directive); a runtime that
     * reads an index for a different ABI refuses it up front and says to regenerate.
     *
     * <p>Bump this when a generated-code-facing helper changes incompatibly. Indexes written
     * before the directive existed are treated as ABI 1, which is what their generators emitted.
     */
    public static final int RUNTIME_ABI = 1;

    private static final String NATIVE_IMAGE_DIRECTORY =
            "META-INF/native-image/com.classwright/classwright";

    private AheadOfTime() {
    }

    /**
     * One generated proxy: its class file and the name to write it under.
     *
     * @param blueprint          what it was generated from
     * @param className          the binary name of the generated class
     * @param classBytes         a complete class file
     * @param routingFingerprint a digest of the callback routing compiled into the class; see
     *                           {@link #routingFingerprint}
     */
    public record Generated(ProxyBlueprint blueprint, String className, byte[] classBytes,
                            String routingFingerprint) {

        /**
         * The path this class belongs at, relative to an output directory.
         *
         * @return a path relative to an output directory, using {@code /} separators
         */
        public String relativePath() {
            return className.replace('.', '/') + ".class";
        }
    }

    /**
     * A {@link Generated} plus the intermediate results it was built from.
     *
     * <p>Internal: the reachability metadata needs the discovered plan and the mirrored
     * constructors, and recomputing them per output would run the user's {@link CallbackFilter} a
     * second time — build-time code, but user code with no promise of being idempotent.
     */
    private record Compiled(Generated generated, ProxyMethods plan,
                            List<java.lang.reflect.Constructor<?>> constructors) {
    }

    /**
     * Generates one proxy class, without writing anything.
     *
     * @param blueprint what to generate
     * @return the generated class file and its name
     */
    public static Generated generate(ProxyBlueprint blueprint) {
        return compile(blueprint).generated();
    }

    private static Compiled compile(ProxyBlueprint blueprint) {
        ProxyMethods.requireProxyable(blueprint.superclass());

        // True, unconditionally: the generated class is placed in the target's own package, so a
        // package-private method is overridable. The runtime lookup path must discover methods with
        // the same answer or the two would disagree about the dispatch table.
        ProxyMethods plan = ProxyMethods.discover(
                blueprint.superclass(), blueprint.interfaces(), true);

        List<java.lang.reflect.Constructor<?>> constructors =
                ProxyClassGenerator.mirrorableConstructors(blueprint.superclass(), true);
        if (constructors.isEmpty()) {
            throw new ClasswrightException(blueprint.superclass().getName()
                    + " has no constructor a subclass could call, so no proxy can be generated "
                    + "for it ahead of time.");
        }

        int[] callbackIndexes = callbackIndexes(blueprint, plan);
        String className = blueprint.generatedClassName();
        ProxySpec spec = new ProxySpec(
                blueprint.superclass(),
                blueprint.interfaces(),
                className.replace('.', '/'),
                plan,
                callbackIndexes,
                blueprint.callbackTypes(),
                blueprint.useFactory(),
                blueprint.interceptDuringConstruction(),
                constructors,
                blueprint.copyAnnotations(),
                blueprint.naming());

        String fingerprint = routingFingerprint(plan, callbackIndexes, blueprint.useFactory(),
                blueprint.interceptDuringConstruction(), blueprint.copyAnnotations());
        return new Compiled(
                new Generated(blueprint, className, ProxyClassGenerator.generate(spec),
                        fingerprint),
                plan, constructors);
    }

    /**
     * Generates every blueprint and writes the classes, the index and the native-image metadata.
     *
     * @param outputDirectory a build output directory, typically {@code target/classes}
     * @param blueprints      what to generate
     * @return what was generated, in the order given
     */
    public static List<Generated> writeTo(Path outputDirectory, List<ProxyBlueprint> blueprints) {
        List<Compiled> compiled = new ArrayList<>(blueprints.size());
        for (ProxyBlueprint blueprint : blueprints) {
            compiled.add(compile(blueprint));
        }
        List<Generated> generated = compiled.stream().map(Compiled::generated).toList();
        rejectDuplicates(generated);

        try {
            for (Generated each : generated) {
                Path target = outputDirectory.resolve(each.relativePath());
                Files.createDirectories(target.getParent());
                Files.write(target, each.classBytes());
            }
            writeString(outputDirectory.resolve(INDEX_RESOURCE), index(generated));
            writeString(outputDirectory.resolve(NATIVE_IMAGE_DIRECTORY + "/reflect-config.json"),
                    reflectConfig(compiled));
            writeString(outputDirectory.resolve(NATIVE_IMAGE_DIRECTORY + "/resource-config.json"),
                    resourceConfig());
        } catch (IOException e) {
            throw new UncheckedIOException("could not write ahead-of-time proxies to "
                    + outputDirectory, e);
        }
        return generated;
    }

    // ==============================================================================================
    // The routing fingerprint
    // ==============================================================================================

    /**
     * A digest of the callback routing a proxy was compiled with.
     *
     * <p>The index key answers "is this the same <em>configuration</em>"; this answers "does the
     * configuration still <em>mean</em> the same thing". The two can diverge: a
     * {@link CallbackFilter} is identified in the key by its class alone, so a stateful filter —
     * one whose {@code accept} answers differently depending on how the instance was set up — can
     * produce a key match while routing methods to entirely different callbacks than the compiled
     * class does. Adopting the class then dispatches methods to the wrong callback, silently.
     *
     * <p>So both halves digest what routing actually <em>is</em>: every dispatched method with the
     * callback index assigned to it, plus the flags that change the generated shape. The build
     * writes the result into the index; {@code Enhancer} recomputes it from its own discovery and
     * its own filter instance, and refuses the entry on a mismatch. The two sides agree given equal
     * inputs because dispatch order is deterministic — discovery sorts by method name and
     * descriptor precisely so that indexes are a function of the configuration alone.
     *
     * <p>Package-private and shared with {@code Enhancer}: one implementation, so the build-time
     * and runtime fingerprints cannot drift apart the way two copies would.
     *
     * @param plan            the discovered methods, in dispatch order
     * @param callbackIndexes the callback index assigned to each dispatch slot
     * @return a hex SHA-256
     */
    static String routingFingerprint(ProxyMethods plan, int[] callbackIndexes, boolean useFactory,
                                     boolean interceptDuringConstruction,
                                     boolean copyAnnotations) {
        StringBuilder text = new StringBuilder();
        for (ProxyMethods.Proxied proxied : plan.proxied()) {
            text.append(proxied.method().getName())
                    .append(com.classwright.core.CwMethodType.of(proxied.method()).descriptor())
                    .append(':').append(callbackIndexes[proxied.index()]).append('\n');
        }
        text.append("useFactory=").append(useFactory)
                .append(" interceptDuringConstruction=").append(interceptDuringConstruction)
                .append(" copyAnnotations=").append(copyAnnotations).append('\n');
        try {
            byte[] hash = MessageDigest.getInstance("SHA-256")
                    .digest(text.toString().getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException impossible) {
            throw new ClasswrightException("SHA-256 is required of every JVM", impossible);
        }
    }

    // ==============================================================================================
    // Outputs
    // ==============================================================================================

    /**
     * The index the runtime reads.
     *
     * <p>Tab-separated text rather than anything structured, on purpose: it is read once at startup,
     * it has to be parseable without a dependency, and when something does not line up the first
     * thing anyone wants is to open it and look.
     *
     * <p>The key can never contain a raw tab or newline — {@link ProxyBlueprint#key()} escapes
     * them — so the three columns are unambiguous.
     */
    static String index(List<Generated> generated) {
        StringBuilder text = new StringBuilder(
                "# Classwright ahead-of-time proxy index. Generated; do not edit.\n"
                        + "# %abi\\t<runtime ABI>, then <key>\\t<generated class>\\t<routing fingerprint>\n"
                        + "%abi\t" + RUNTIME_ABI + "\n");
        for (Generated each : generated) {
            text.append(each.blueprint().key()).append('\t').append(each.className())
                    .append('\t').append(each.routingFingerprint()).append('\n');
        }
        return text.toString();
    }

    /**
     * Reachability metadata, narrowed to what the runtime actually touches reflectively.
     *
     * <p>Registering everything with {@code allDeclared*} would work, but reflection metadata is
     * what defeats the native-image shrinker: every registered member is compiled in and every
     * method it reaches with it. The adopted-proxy path is small and known, so the metadata can be
     * exact. What the runtime does, member by member:
     *
     * <ul>
     *   <li><strong>The generated class</strong> is resolved by name ({@code Class.forName} in
     *       {@link AotProxies}); its {@code CW$init} is invoked through a method-handle lookup; its
     *       declared <em>fields</em> are enumerated (the method-count gate counts {@code method$}
     *       slots, callback binding finds {@code callback$} slots, and {@code CW$lookup} is read
     *       reflectively); and its declared <em>constructors</em> are found through the lookup when
     *       instances are created. Hence: the {@code CW$init} method, all declared fields, all
     *       declared constructors. The overridden methods themselves are invoked virtually, never
     *       reflectively, so they need no entry.</li>
     *   <li><strong>The target hierarchy</strong> — the superclass chain and every interface in the
     *       closure — is walked with {@code getDeclaredMethods()} by method discovery, which is a
     *       query, not an invocation: {@code queryAllDeclaredMethods}. The superclass additionally
     *       has its constructors enumerated to decide which to mirror:
     *       {@code queryAllDeclaredConstructors}.</li>
     *   <li><strong>The proxied methods</strong> are registered for <em>invocation</em> on their
     *       declaring classes. Two reasons, both load-bearing: {@code Enhancer} calls
     *       {@code setAccessible(true)} on each (best-effort, but the failure it tolerates is a
     *       {@code RuntimeException}, and an unregistered member in a native image throws an
     *       {@code Error} instead), and interceptors are handed the {@code Method} with every
     *       expectation that {@code Method.invoke} works.</li>
     * </ul>
     *
     * <p>Deliberately absent: callback types (their fields and call sites are compiled into the
     * generated class; nothing reflects on them — verified against {@code CallbackKind}, which
     * resolves kinds with {@code isAssignableFrom} alone) and the {@link CallbackFilter} (it runs
     * at build time only; at runtime the {@code Enhancer} already holds an instance and never
     * instantiates the class).
     */
    static String reflectConfig(List<Compiled> compiled) {
        Map<String, TypeMetadata> types = new TreeMap<>();
        for (Compiled each : compiled) {
            ProxyBlueprint blueprint = each.generated().blueprint();

            TypeMetadata proxy = types.computeIfAbsent(each.generated().className(),
                    TypeMetadata::new);
            proxy.allDeclaredFields = true;
            proxy.allDeclaredConstructors = true;
            proxy.methods.add(ProxyClassGenerator.INIT_METHOD
                    + "(java.lang.reflect.Method[],com.classwright.proxy.MethodProxy[],"
                    + "java.lang.invoke.MethodHandles$Lookup)");

            for (Class<?> type : hierarchyOf(blueprint)) {
                types.computeIfAbsent(type.getName(), TypeMetadata::new)
                        .queryAllDeclaredMethods = true;
            }
            types.computeIfAbsent(blueprint.superclass().getName(), TypeMetadata::new)
                    .queryAllDeclaredConstructors = true;

            for (ProxyMethods.Proxied proxied : each.plan().proxied()) {
                java.lang.reflect.Method method = proxied.method();
                TypeMetadata declaring = types.computeIfAbsent(
                        method.getDeclaringClass().getName(), TypeMetadata::new);
                StringJoiner parameters = new StringJoiner(",");
                for (Class<?> parameter : method.getParameterTypes()) {
                    parameters.add(parameter.getTypeName());
                }
                declaring.methods.add(method.getName() + "(" + parameters + ")");
            }
        }

        StringJoiner entries = new StringJoiner(",\n  ", "[\n  ", "\n]\n");
        for (TypeMetadata each : types.values()) {
            entries.add(each.toJson());
        }
        return entries.toString();
    }

    /**
     * Every type method discovery will call {@code getDeclaredMethods()} on for this blueprint.
     *
     * <p>The same set {@code ProxyMethods} walks: the superclass chain, plus the transitive
     * interface closure of the configured interfaces and of every class in the chain. Recomputed
     * here as a set because only membership matters for metadata, not the override order the
     * discovery walk depends on.
     */
    private static Set<Class<?>> hierarchyOf(ProxyBlueprint blueprint) {
        Set<Class<?>> types = new LinkedHashSet<>();
        for (Class<?> type = blueprint.superclass(); type != null; type = type.getSuperclass()) {
            types.add(type);
            for (Class<?> each : type.getInterfaces()) {
                collectInterfaces(each, types);
            }
        }
        for (Class<?> each : blueprint.interfaces()) {
            collectInterfaces(each, types);
        }
        return types;
    }

    private static void collectInterfaces(Class<?> type, Set<Class<?>> into) {
        if (into.add(type)) {
            for (Class<?> parent : type.getInterfaces()) {
                collectInterfaces(parent, into);
            }
        }
    }

    /** One reflect-config entry in the making; flags accumulate across blueprints. */
    private static final class TypeMetadata {

        final String name;
        boolean queryAllDeclaredMethods;
        boolean queryAllDeclaredConstructors;
        boolean allDeclaredFields;
        boolean allDeclaredConstructors;

        /** Invocable methods as {@code name(param,param)} signatures; sorted, deduplicated. */
        final Set<String> methods = new TreeSet<>();

        TypeMetadata(String name) {
            this.name = name;
        }

        String toJson() {
            StringBuilder json = new StringBuilder("{\"name\": \"").append(escape(name)).append('"');
            if (queryAllDeclaredMethods) {
                json.append(", \"queryAllDeclaredMethods\": true");
            }
            if (queryAllDeclaredConstructors) {
                json.append(", \"queryAllDeclaredConstructors\": true");
            }
            if (allDeclaredFields) {
                json.append(", \"allDeclaredFields\": true");
            }
            if (allDeclaredConstructors) {
                json.append(", \"allDeclaredConstructors\": true");
            }
            if (!methods.isEmpty()) {
                StringJoiner list = new StringJoiner(", ", "[", "]");
                for (String signature : methods) {
                    int open = signature.indexOf('(');
                    String parameters = signature.substring(open + 1, signature.length() - 1);
                    StringJoiner parameterList = new StringJoiner(", ", "[", "]");
                    if (!parameters.isEmpty()) {
                        for (String parameter : parameters.split(",")) {
                            parameterList.add('"' + escape(parameter) + '"');
                        }
                    }
                    list.add("{\"name\": \"" + escape(signature.substring(0, open))
                            + "\", \"parameterTypes\": " + parameterList + "}");
                }
                json.append(", \"methods\": ").append(list);
            }
            return json.append('}').toString();
        }
    }

    static String resourceConfig() {
        return "{\n  \"resources\": {\n    \"includes\": [\n"
                + "      {\"pattern\": \"\\\\QMETA-INF/classwright/proxies.index\\\\E\"}\n"
                + "    ]\n  }\n}\n";
    }

    // ==============================================================================================
    // Internals
    // ==============================================================================================

    /** Asks the filter which callback handles each method, exactly as {@code Enhancer} does. */
    private static int[] callbackIndexes(ProxyBlueprint blueprint, ProxyMethods plan) {
        int[] indexes = new int[plan.proxied().size()];
        if (blueprint.filter() == null) {
            return indexes;
        }
        CallbackFilter filter = instantiate(blueprint.filter());
        for (ProxyMethods.Proxied proxied : plan.proxied()) {
            int index = filter.accept(proxied.method());
            if (index < 0 || index >= blueprint.callbackTypes().size()) {
                throw new ClasswrightException("the CallbackFilter returned " + index + " for "
                        + proxied.method() + ", but only " + blueprint.callbackTypes().size()
                        + " callback types were declared");
            }
            indexes[proxied.index()] = index;
        }
        return indexes;
    }

    private static CallbackFilter instantiate(Class<? extends CallbackFilter> type) {
        try {
            java.lang.reflect.Constructor<? extends CallbackFilter> constructor =
                    type.getDeclaredConstructor();
            constructor.setAccessible(true);
            return constructor.newInstance();
        } catch (ReflectiveOperationException | RuntimeException e) {
            throw new ClasswrightException(type.getName() + " could not be created. A CallbackFilter "
                    + "used in a blueprint needs an accessible no-argument constructor, because the "
                    + "build has to run it to decide which callback handles which method.", e);
        }
    }

    /**
     * Two blueprints that differ but generate the same name would silently overwrite each other.
     *
     * <p>The name is a digest of the key, so this means a hash collision or the same blueprint
     * listed twice. Both are worth saying out loud rather than resolving by last-write-wins.
     */
    private static void rejectDuplicates(List<Generated> generated) {
        Set<String> names = new LinkedHashSet<>();
        for (Generated each : generated) {
            if (!names.add(each.className())) {
                throw new ClasswrightException("two blueprints generate the same class name, "
                        + each.className() + ". If they are the same configuration, list it once; "
                        + "if not, this is a digest collision — please report it.");
            }
        }
    }

    private static void writeString(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
