package com.classwright.proxy;

import java.lang.reflect.Method;

/**
 * Decides which callback handles which method.
 *
 * <p>Without one, every proxied method uses the single callback given to
 * {@link Enhancer#setCallback}. With one, {@link Enhancer#setCallbacks} supplies an array and this
 * chooses an index per method — so a proxy can intercept its business methods, leave
 * {@code toString} alone with {@link NoOp}, and stub something else with a {@link FixedValue}.
 *
 * <p>The filter is consulted once per method at <em>generation</em> time, never per call. The
 * decision is baked into the generated bytecode, which is why per-method dispatch costs nothing at
 * runtime.
 *
 * <h2>Implementations must define equals and hashCode</h2>
 *
 * <p>The filter is part of the cache key that decides whether an existing generated class can be
 * reused. Two enhancers configured identically but with distinct filter instances must be
 * recognised as equivalent, and with the default identity-based {@code equals} they will not be:
 * every request generates a fresh class and the cache never hits.
 *
 * <p>The simplest way to satisfy this is a stateless filter declared as a named class, for which
 * comparing {@code getClass()} is enough. CGLib made the same requirement, and the usual symptom
 * of ignoring it was a slow metaspace leak rather than an error.
 */
public interface CallbackFilter {

    /**
     * The index into the callback array for this method.
     *
     * @param method a method that will be proxied
     * @return the zero-based index of the callback to use
     */
    int accept(Method method);

    /**
     * Two filters must compare equal when they would make the same decisions.
     *
     * @param other the object to compare with
     * @return whether the two are interchangeable for caching purposes
     */
    @Override
    boolean equals(Object other);

    @Override
    int hashCode();
}
