package com.classwright.proxy;

import com.classwright.ClasswrightException;

import java.io.Serializable;

/**
 * A drop-in replacement for {@link java.lang.reflect.Proxy}, backed by generated subclasses.
 *
 * <pre>{@code
 * Service service = (Service) Proxy.newProxyInstance(
 *         loader, new Class<?>[]{Service.class},
 *         (proxy, method, args) -> "intercepted");
 * }</pre>
 *
 * <p>Mirrors {@code net.sf.cglib.proxy.Proxy}, which existed so that code written against the JDK's
 * dynamic proxies could move to CGLib without changing shape. The same reasoning applies here.
 *
 * <p><strong>There is usually no reason to prefer this over the JDK's own.</strong> For a pure
 * interface proxy the JDK version is well optimised, needs no code generation, and has no
 * dependency. The measurements bear that out: the JDK proxy and a Classwright proxy dispatch within
 * noise of one another. Use this when migrating existing CGLib code, or when the same call site has
 * to accept both interface and class proxies; reach for {@link Enhancer} directly for anything new.
 *
 * <p>The {@code loader} argument is accepted and ignored. Classwright places generated classes
 * beside the interfaces being implemented, which is both more reliable and the only thing that
 * works when a hidden class is involved. CGLib's equivalent honoured it; keeping the parameter
 * means existing call sites compile unchanged.
 */
public final class Proxy implements Serializable {

    private static final long serialVersionUID = 1L;

    private Proxy() {
    }

    /**
     * Creates a proxy implementing the given interfaces, routing every call to {@code handler}.
     *
     * @param loader     accepted for source compatibility and ignored; see the class documentation
     * @param interfaces the interfaces to implement
     * @param handler    handles every call
     * @return the proxy
     */
    public static Object newProxyInstance(ClassLoader loader, Class<?>[] interfaces,
                                          InvocationHandler handler) {
        if (handler == null) {
            throw new ClasswrightException("handler must not be null");
        }
        Enhancer enhancer = new Enhancer();
        enhancer.setInterfaces(requireInterfaces(interfaces));
        enhancer.setCallback(handler);
        enhancer.setUseFactory(true);
        return enhancer.create();
    }

    /**
     * The class a proxy for these interfaces would have.
     *
     * @param loader     accepted for source compatibility and ignored
     * @param interfaces the interfaces to implement
     * @return the generated class
     */
    public static Class<?> getProxyClass(ClassLoader loader, Class<?>[] interfaces) {
        Enhancer enhancer = new Enhancer();
        enhancer.setInterfaces(requireInterfaces(interfaces));
        enhancer.setCallbackTypes(InvocationHandler.class);
        enhancer.setUseFactory(true);
        return enhancer.createClass();
    }

    /**
     * Whether a class was generated by Classwright.
     *
     * @param type any class
     * @return whether it is a generated proxy
     */
    public static boolean isProxyClass(Class<?> type) {
        return ProxySupport.isGeneratedProxy(type);
    }

    /**
     * The handler a proxy was created with.
     *
     * @param proxy a proxy created by {@link #newProxyInstance}
     * @return its invocation handler
     * @throws ClasswrightException if the object is not such a proxy
     */
    public static InvocationHandler getInvocationHandler(Object proxy) {
        if (!(proxy instanceof Factory factory)) {
            throw new ClasswrightException((proxy == null ? "null" : proxy.getClass().getName())
                    + " is not a Classwright proxy with a Factory interface");
        }
        Callback callback = factory.getCallback(0);
        if (!(callback instanceof InvocationHandler handler)) {
            throw new ClasswrightException("this proxy's callback is a "
                    + (callback == null ? "null" : callback.getClass().getName())
                    + ", not an InvocationHandler. It was not created through Proxy.");
        }
        return handler;
    }

    private static Class<?>[] requireInterfaces(Class<?>[] interfaces) {
        if (interfaces == null || interfaces.length == 0) {
            throw new ClasswrightException("at least one interface is required");
        }
        for (Class<?> each : interfaces) {
            if (each == null || !each.isInterface()) {
                throw new ClasswrightException((each == null ? "null" : each.getName())
                        + " is not an interface. Use Enhancer to subclass a class.");
            }
        }
        return interfaces;
    }
}
