package com.classwright.proxy;

import com.classwright.ClasswrightException;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles.Lookup;
import java.lang.invoke.MethodType;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Runtime helpers that generated proxies call into.
 *
 * <p><strong>Not part of the public API.</strong> Public only because generated classes live in the
 * target's package rather than Classwright's.
 *
 * <p>Anything here is work that would be tedious and error-prone to express in bytecode and costs
 * nothing to do in Java, because it happens once per proxy <em>instance</em> rather than once per
 * call. Constructor selection is the main example. Keeping it out of the generator also keeps the
 * generator small, which matters when its failures are {@code VerifyError}s.
 */
@com.classwright.Internal
public final class ProxySupport {

    /** The static field every generated proxy carries, holding a lookup on itself. */
    static final String LOOKUP_FIELD = "CW$lookup";

    /**
     * Lookups recovered from generated proxy classes.
     *
     * <p>A {@link ClassValue} rather than a map, for the same reason the generation cache uses one:
     * entries are stored on the key class itself, so nothing global holds a reference to a proxy
     * class and unloading still works. The value references the class it is keyed by, which is a
     * cycle the collector handles as a unit.
     */
    private static final ClassValue<Lookup> LOOKUPS = new ClassValue<>() {
        @Override
        protected Lookup computeValue(Class<?> proxyClass) {
            try {
                java.lang.reflect.Field field = proxyClass.getDeclaredField(LOOKUP_FIELD);
                field.setAccessible(true);
                Lookup lookup = (Lookup) field.get(null);
                if (lookup == null) {
                    throw new ClasswrightException(proxyClass.getName()
                            + " has not been initialised; " + ProxyClassGenerator.INIT_METHOD
                            + " must run before any instance is created");
                }
                return lookup;
            } catch (ReflectiveOperationException e) {
                throw new ClasswrightException(proxyClass.getName()
                        + " is not a Classwright proxy: it has no " + LOOKUP_FIELD + " field", e);
            }
        }
    };

    /**
     * Per-proxy-class runtime metadata: the no-argument constructor handle directly, other
     * signatures behind a small map.
     *
     * <p>The split is the point. Creating an instance from a cached class is the steady state of
     * the whole library, and almost every creation uses the no-argument constructor — so the
     * common path should be one {@link ClassValue} read, one field read, and the call. Building a
     * {@link MethodType} and probing a map per instance is machinery the general path needs and
     * the common path does not.
     *
     * <p>A {@link ClassValue}, for the same no-leak reason as {@code LOOKUPS} above.
     */
    private static final class ProxyRuntime {

        /** {@code ()Object}, derived on first use; racy publication of equivalents is fine. */
        volatile MethodHandle noArgConstructor;

        final Map<MethodType, MethodHandle> constructors = new ConcurrentHashMap<>(2);
    }

    private static final ClassValue<ProxyRuntime> RUNTIMES = new ClassValue<>() {
        @Override
        protected ProxyRuntime computeValue(Class<?> proxyClass) {
            return new ProxyRuntime();
        }
    };

    private ProxySupport() {
    }

    /**
     * Creates an instance of an already-generated proxy class.
     *
     * <p>The overload used when only the {@code Class} is to hand, as happens on a cache hit.
     *
     * @param proxyClass     a class generated by Classwright
     * @param parameterTypes the superclass constructor signature to invoke
     * @param arguments      the constructor arguments
     * @param callbacks      the callbacks to bind
     * @return the new proxy
     */
    public static Object newInstance(Class<?> proxyClass, Class<?>[] parameterTypes,
                                     Object[] arguments, Callback[] callbacks) {
        if (parameterTypes.length == 0) {
            ProxyRuntime runtime = RUNTIMES.get(proxyClass);
            MethodHandle constructor = runtime.noArgConstructor;
            if (constructor == null) {
                constructor = deriveNoArgConstructor(proxyClass, runtime);
            }
            CallbackRegistry.bind(proxyClass, callbacks);
            try {
                return constructor.invokeExact();
            } catch (Throwable t) {
                throw constructionFailure(proxyClass, t);
            } finally {
                CallbackRegistry.clear();
            }
        }
        MethodHandle constructor = constructorFor(proxyClass,
                MethodType.methodType(void.class, parameterTypes));
        return invoke(proxyClass, constructor, arguments, callbacks);
    }

    private static MethodHandle deriveNoArgConstructor(Class<?> proxyClass, ProxyRuntime runtime) {
        try {
            MethodHandle derived = LOOKUPS.get(proxyClass)
                    .findConstructor(proxyClass, MethodType.methodType(void.class))
                    .asType(MethodType.methodType(Object.class));
            runtime.noArgConstructor = derived;
            return derived;
        } catch (ReflectiveOperationException e) {
            throw new ClasswrightException("the generated proxy has no constructor matching "
                    + "()void. A proxy only mirrors the superclass constructors that were "
                    + "visible to it.", e);
        }
    }

    /**
     * A ready-to-invoke constructor handle, cached per proxy class and signature.
     *
     * <p>Deriving one means a lookup plus two adaptations ({@code asSpreader} and {@code asType}),
     * which together cost far more than the constructor call itself. Rebuilding it per instance
     * made creating a proxy from a cached class several times more expensive than it needed to be.
     *
     * <p>Cached on the class through a {@link ClassValue}, so nothing global holds a proxy class
     * alive and unloading still works.
     */
    private static MethodHandle constructorFor(Class<?> proxyClass, MethodType signature) {
        return RUNTIMES.get(proxyClass).constructors.computeIfAbsent(signature, wanted -> {
            Lookup lookup = LOOKUPS.get(proxyClass);
            try {
                return lookup.findConstructor(proxyClass, wanted)
                        .asSpreader(Object[].class, wanted.parameterCount())
                        .asType(MethodType.methodType(Object.class, Object[].class));
            } catch (ReflectiveOperationException e) {
                throw new ClasswrightException("the generated proxy has no constructor matching "
                        + wanted + ". A proxy only mirrors the superclass constructors that were "
                        + "visible to it.", e);
            }
        });
    }

    private static Object invoke(Class<?> proxyClass, MethodHandle constructor, Object[] arguments,
                                 Callback[] callbacks) {
        CallbackRegistry.bind(proxyClass, callbacks);
        try {
            return constructor.invokeExact(arguments);
        } catch (Throwable t) {
            throw constructionFailure(proxyClass, t);
        } finally {
            CallbackRegistry.clear();
        }
    }

    /** Always throws; declared to return so callers can write {@code throw}. */
    private static RuntimeException constructionFailure(Class<?> proxyClass, Throwable t) {
        if (t instanceof Error error) {
            // An OutOfMemoryError or LinkageError is not ours to reinterpret.
            throw error;
        }
        if (t instanceof RuntimeException runtime) {
            // The superclass constructor's own exception should surface as itself.
            throw runtime;
        }
        throw new ClasswrightException(
                "could not construct a proxy of " + proxyClass.getName() + ": " + t, t);
    }

    /**
     * Creates another instance of an already-generated proxy class.
     *
     * <p>Goes through the {@link Lookup} the class was defined with, because a hidden class cannot
     * be named by any other class's bytecode and so cannot be reached reflectively either.
     *
     * <p>The callbacks are parked in {@link CallbackRegistry} for the duration of the constructor,
     * which is how they reach the instance before any of its methods can run.
     *
     * @param lookup         a lookup on the generated class
     * @param parameterTypes the superclass constructor signature to invoke
     * @param arguments      the constructor arguments
     * @param callbacks      the callbacks to bind
     * @return the new proxy
     */
    public static Object newInstance(Lookup lookup, Class<?>[] parameterTypes, Object[] arguments,
                                     Callback[] callbacks) {
        return newInstance(lookup.lookupClass(), parameterTypes, arguments, callbacks);
    }

    /**
     * Setters for a proxy class's callback fields, in slot order, derived once per class.
     *
     * <p>Backs {@link #bindPending}: the fields are private members of a (usually hidden) class,
     * so the only way in from Java is through the {@link Lookup} the class carries.
     */
    private static final ClassValue<MethodHandle[]> CALLBACK_SETTERS = new ClassValue<>() {
        @Override
        protected MethodHandle[] computeValue(Class<?> proxyClass) {
            java.util.List<java.lang.reflect.Field> fields = new java.util.ArrayList<>();
            for (java.lang.reflect.Field field : proxyClass.getDeclaredFields()) {
                // Both naming conventions mark callback slots the same way: <prefix>callback$<n>.
                if (Callback.class.isAssignableFrom(field.getType())
                        && field.getName().contains("callback$")) {
                    fields.add(field);
                }
            }
            fields.sort(java.util.Comparator.comparingInt(
                    field -> Integer.parseInt(field.getName().substring(
                            field.getName().lastIndexOf('$') + 1))));
            Lookup lookup = LOOKUPS.get(proxyClass);
            MethodHandle[] setters = new MethodHandle[fields.size()];
            for (int i = 0; i < setters.length; i++) {
                try {
                    setters[i] = lookup.unreflectSetter(fields.get(i))
                            .asType(MethodType.methodType(void.class, Object.class,
                                    Callback.class));
                } catch (IllegalAccessException e) {
                    throw new ClasswrightException("cannot reach the callback fields of "
                            + proxyClass.getName(), e);
                }
            }
            return setters;
        }
    };

    /**
     * Binds parked or registered callbacks into an instance whose fields are still null.
     *
     * <p>Generated methods call this from their callback-is-null branch, then re-read the field.
     * It serves two flows, both of which CGLib served with {@code CGLIB$BIND_CALLBACKS}:
     *
     * <ul>
     * <li><strong>Construction-time interception.</strong> Nothing can write the fields before
     * {@code super()} returns, but a superclass constructor may call an overridable method on
     * {@code this}. The override lands here, finds the construction's own parked frame — matched
     * by exact class, so a nested construction of some other proxy cannot be confused with it —
     * and binds mid-construction. This is why, as in CGLib, callbacks are active during the
     * superclass constructor by default.</li>
     * <li><strong>Constructor-less instances.</strong> Objenesis and its kin skip constructors
     * entirely; such an instance picks up callbacks registered for its class on its first
     * dispatched call.</li>
     * </ul>
     *
     * <p>When nothing is parked or registered this is two cheap reads, and the caller falls
     * through to the original method exactly as before.
     *
     * @param proxy the instance to bind
     */
    public static void bindPending(Object proxy) {
        Callback[] registered = CallbackRegistry.pendingFor(proxy.getClass());
        if (registered == null) {
            registered = CallbackRegistry.registeredFor(proxy.getClass());
        }
        if (registered == null) {
            return;
        }
        MethodHandle[] setters = CALLBACK_SETTERS.get(proxy.getClass());
        int slots = Math.min(setters.length, registered.length);
        for (int i = 0; i < slots; i++) {
            if (registered[i] == null) {
                continue;      // an unfilled slot stays unbound and dispatches to the original
            }
            try {
                setters[i].invokeExact(proxy, registered[i]);
            } catch (Throwable t) {
                throw new ClasswrightException("could not bind callback " + i + " of "
                        + proxy.getClass().getName() + ": " + t, t);
            }
        }
    }

    /**
     * Accessors for a proxy class's lazy-delegate fields, indexed by callback slot.
     *
     * <p>Sparse: only slots whose callback kind caches an instance have a field; other entries
     * stay {@code null}. Backs {@link #lazyInitialise}.
     */
    private static final ClassValue<MethodHandle[][]> LAZY_ACCESSORS = new ClassValue<>() {
        @Override
        protected MethodHandle[][] computeValue(Class<?> proxyClass) {
            java.util.TreeMap<Integer, java.lang.reflect.Field> bySlot = new java.util.TreeMap<>();
            for (java.lang.reflect.Field field : proxyClass.getDeclaredFields()) {
                if (field.getType() == Object.class && field.getName().contains("lazy$")) {
                    bySlot.put(Integer.parseInt(field.getName()
                            .substring(field.getName().lastIndexOf('$') + 1)), field);
                }
            }
            int slots = bySlot.isEmpty() ? 0 : bySlot.lastKey() + 1;
            MethodHandle[] getters = new MethodHandle[slots];
            MethodHandle[] setters = new MethodHandle[slots];
            Lookup lookup = LOOKUPS.get(proxyClass);
            try {
                for (java.util.Map.Entry<Integer, java.lang.reflect.Field> entry
                        : bySlot.entrySet()) {
                    getters[entry.getKey()] = lookup.unreflectGetter(entry.getValue())
                            .asType(MethodType.methodType(Object.class, Object.class));
                    setters[entry.getKey()] = lookup.unreflectSetter(entry.getValue())
                            .asType(MethodType.methodType(void.class, Object.class,
                                    Object.class));
                }
            } catch (IllegalAccessException e) {
                throw new ClasswrightException(
                        "cannot reach the lazy fields of " + proxyClass.getName(), e);
            }
            return new MethodHandle[][]{getters, setters};
        }
    };

    /**
     * Resolves a {@link LazyLoader}'s delegate exactly once per instance.
     *
     * <p>Generated methods take the fast path themselves — a volatile field read — and only land
     * here when the field is still null. The monitor makes the first resolution
     * <em>at-most-once</em>, which is what CGLib's synchronised accessor guaranteed and what
     * migrated loaders with non-idempotent construction rely on; the lock is never touched again
     * once the field is set. A {@code null} result is returned but not cached, so the next call
     * retries — also CGLib's behaviour.
     *
     * @param proxy  the proxy whose delegate is being resolved
     * @param loader the callback bound to the slot
     * @param slot   the callback slot index
     * @return the delegate to dispatch to
     */
    public static Object lazyInitialise(Object proxy, LazyLoader loader, int slot) {
        MethodHandle[][] accessors = LAZY_ACCESSORS.get(proxy.getClass());
        MethodHandle getter = accessors[0][slot];
        MethodHandle setter = accessors[1][slot];
        synchronized (proxy) {
            try {
                Object existing = getter.invokeExact(proxy);
                if (existing != null) {
                    return existing;
                }
                Object created = loader.loadObject();
                if (created != null) {
                    setter.invokeExact(proxy, created);
                }
                return created;
            } catch (Throwable t) {
                // The generated call previously invoked loadObject() directly, letting checked
                // exceptions propagate raw; a Java-level wrapper must not start wrapping them.
                throw sneakyThrow(t);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static <T extends Throwable> RuntimeException sneakyThrow(Throwable t) throws T {
        throw (T) t;
    }

    /**
     * Whether a class was generated by Classwright.
     *
     * <p>Detected by the presence of the lookup field every generated proxy carries, rather than by
     * a name pattern. A name test would be defeated by any class that happened to contain
     * {@code $$}, and a global registry of generated classes would keep them all alive.
     *
     * @param type any class
     * @return whether it is a generated proxy
     */
    public static boolean isGeneratedProxy(Class<?> type) {
        if (type == null) {
            return false;
        }
        try {
            java.lang.reflect.Field marker = type.getDeclaredField(LOOKUP_FIELD);
            // Type alone is spoofable by an ordinary class that happens to declare the same
            // field; the generator's exact shape — static and synthetic — is not something
            // source code can produce by accident (javac refuses the identifier-with-$ only by
            // convention, but it cannot mark a field synthetic at all).
            return marker.getType() == Lookup.class
                    && java.lang.reflect.Modifier.isStatic(marker.getModifiers())
                    && marker.isSynthetic();
        } catch (NoSuchFieldException | RuntimeException notAProxy) {
            return false;
        }
    }

    /**
     * Checks that a replacement callback is of the type the proxy was generated for.
     *
     * <p>Callback types are compiled into the generated class: each one has a field of its declared
     * interface type, and the method bodies call that interface directly. A proxy generated for a
     * {@link NoOp} therefore cannot later be handed a {@link MethodInterceptor} — there is nowhere
     * to put it and no code to call it. CGLib had the same constraint.
     *
     * <p>Without this the failure is a bare {@link ClassCastException} from inside generated code,
     * which says what happened but not why.
     *
     * @param callback the replacement, may be {@code null} to clear the slot
     * @param expected the type this slot was generated for
     * @return {@code callback}, so the generated code can chain the cast
     */
    public static Callback requireCallbackType(Callback callback, Class<?> expected) {
        if (callback != null && !expected.isInstance(callback)) {
            throw new ClasswrightException("this proxy was generated for a "
                    + expected.getSimpleName() + " in that callback slot, but was given a "
                    + callback.getClass().getName() + ".\n"
                    + "Callback types are compiled into the generated class, so a callback can "
                    + "only be replaced by one of the same type. Generate a new proxy with "
                    + "Enhancer if a different kind of callback is needed.");
        }
        return callback;
    }

    /**
     * Copies a callback array so that a proxy's internal state cannot be mutated from outside.
     *
     * @param callbacks the array to copy; may be {@code null}
     * @return a defensive copy, or an empty array
     */
    public static Callback[] copy(Callback[] callbacks) {
        return callbacks == null ? new Callback[0] : callbacks.clone();
    }

}
