/**
 * Classwright &mdash; runtime code generation for the JVM.
 *
 * <p>This module has <strong>no dependencies</strong>, on purpose. It requires nothing beyond
 * {@code java.base}, so there is nothing to shade, nothing to conflict with an application's own
 * libraries, and no third party whose maintenance schedule can strand us on an old JDK. That was
 * the fate of CGLib, which shaded a pinned copy of ASM and stopped being able to read newer class
 * files. See {@code docs/RESEARCH.md}.
 *
 * <p><strong>Exported does not mean supported.</strong> Generated classes live in their
 * <em>target's</em> package and module, so the runtime helpers their bytecode actually calls
 * ({@code ProxySupport}, {@code CallbackRegistry}, {@code SuperDispatcher},
 * {@code RuntimeConstants}, {@code BulkAccessException}) must be {@code public} in exported
 * packages &mdash; the JVM's accessibility rules leave no choice. Those types are annotated
 * {@link com.classwright.Internal} and excluded from the member-level API freeze: they are the
 * generated-code runtime ABI, versioned with the generator, not a user contract. The supported
 * API is what the API snapshot lists member by member. Note the boundary runs both ways:
 * {@code com.classwright.runtime.unsafe} is <em>not</em> exported, precisely because generated
 * bytecode never references it &mdash; allocation goes through {@code Instantiator} in Java.
 * Do not reintroduce that export; nothing outside this module may need it.
 *
 * <p>Packages are added to the exports list as each phase lands; see {@code docs/PLAN.md}.
 */
module com.classwright {
    exports com.classwright;
    exports com.classwright.core;
    exports com.classwright.runtime;
    // com.classwright.runtime.unsafe is deliberately NOT exported: the mechanisms live behind
    // Capabilities and Instantiator, generated bytecode never references the package, and an
    // export would make replaceable JDK-specific plumbing look like API.
    exports com.classwright.proxy;
    exports com.classwright.reflect;
    exports com.classwright.beans;
}
