package com.classwright.core.fixtures;

import java.util.ArrayList;
import java.util.List;

/**
 * Collects the arguments a generated proxy-shaped class passes out to a callback.
 *
 * <p>Static, because generated classes are defined in a throwaway child loader whose parent is the
 * test's own loader. That means the generated code and the test see the very same
 * {@code Recorder} class, so static state passes between them without any wiring.
 */
public final class Recorder {

    private static final List<Object[]> CALLS = new ArrayList<>();

    private Recorder() {
    }

    /** Called from generated bytecode. */
    public static void record(Object[] arguments) {
        CALLS.add(arguments);
    }

    public static List<Object[]> calls() {
        return CALLS;
    }

    public static void reset() {
        CALLS.clear();
    }
}
