package com.classwright.beans;

import com.classwright.ClasswrightException;
import com.classwright.core.AccessFlags;
import com.classwright.core.CodeBuilder;
import com.classwright.core.CwClassWriter;
import com.classwright.core.CwMethodType;
import com.classwright.core.CwType;
import com.classwright.runtime.ClassDefiner;
import com.classwright.runtime.DefinedClass;
import com.classwright.runtime.GenerationCache;
import com.classwright.runtime.Instantiator;

import java.lang.reflect.Method;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Copies matching properties from one bean to another, without reflection.
 *
 * <pre>{@code
 * BeanCopier copier = BeanCopier.create(OrderEntity.class, OrderDto.class, false);
 * copier.copy(entity, dto, null);
 * }</pre>
 *
 * <p>The property matching happens once, at generation time; the generated {@code copy} method is a
 * straight sequence of {@code target.setX(source.getX())} calls. For a bean with twenty properties
 * that is twenty direct calls rather than forty reflective ones, which is the entire reason this
 * exists.
 *
 * <p>Two different type relations are at work, deliberately kept apart. <em>Within</em> each
 * bean, which getter and setter form a property follows the JavaBeans rules — a property's own
 * setter takes the getter's type or a subtype (see {@code BeanProperties}); cross-bean copying
 * never widens a bean's own property definition. <em>Between</em> the two beans, source and
 * target properties are matched by <strong>name and assignable type</strong>, as CGLib matched
 * them: a {@code String getName()} on the source feeds {@code void setName(String)} and also
 * {@code void setName(CharSequence)} on the target, since the value can be passed as-is —
 * assignability here runs from the source's read type into the target's own resolved setter.
 * Primitives must match exactly. Anything unmatched is silently skipped, which is CGLib's
 * behaviour and occasionally surprising — {@link #describeMapping()} exists so it can be
 * checked.
 *
 * <p>Supply a {@link Converter} for types that do not line up, having created the copier with
 * {@code useConverter} set. A copier created without one has no converter code in it at all, so it
 * pays nothing for the option.
 */
public abstract class BeanCopier {

    private String mapping = "";

    /**
     * For generated subclasses. Use {@link #create} to obtain an instance.
     */
    protected BeanCopier() {
    }

    /**
     * Creates a copier between two bean types.
     *
     * @param source       the class to read from
     * @param target       the class to write to
     * @param useConverter whether {@link #copy} will be given a {@link Converter}
     * @return the copier
     */
    public static BeanCopier create(Class<?> source, Class<?> target, boolean useConverter) {
        if (source == null || target == null) {
            throw new ClasswrightException("both source and target classes are required");
        }
        // Copiers are stateless — property matching is baked into the generated bytecode — so one
        // instance per configuration serves every caller. CGLib cached the generated class the
        // same way; regenerating per call turned each create() into a class definition.
        Class<?> generated = GenerationCache.computeIfAbsent(target,
                new CopierKey(GenerationCache.WeakPart.of(source), useConverter),
                () -> defineCopier(source, target, useConverter));
        BeanCopier copier = INSTANCES.get(generated).get();
        if (copier == null) {
            throw new ClasswrightException("no copier registered for " + generated.getName());
        }
        return copier;
    }

    /**
     * The generation-cache key. Anchored on the target class, so the source appears here; the
     * anchor itself carries the target dimension. The source is held weakly: the anchor can
     * outlive the source's loader (a long-lived target fed from an application's classes), and
     * a key must not pin what it merely names.
     */
    private record CopierKey(GenerationCache.WeakPart source, boolean useConverter)
            implements GenerationCache.StaleKey {

        @Override
        public boolean isStale() {
            return source.isStale();
        }
    }

    /** One shared, immutable copier per generated class; see {@link BeanMap} for the pattern. */
    private static final ClassValue<AtomicReference<BeanCopier>> INSTANCES = new ClassValue<>() {
        @Override
        protected AtomicReference<BeanCopier> computeValue(Class<?> generated) {
            return new AtomicReference<>();
        }
    };

    private static Class<?> defineCopier(Class<?> source, Class<?> target, boolean useConverter) {
        Map<String, BeanProperties.Property> sourceProperties = BeanProperties.of(source);
        Map<String, BeanProperties.Property> targetProperties = BeanProperties.of(target);

        List<Pairing> pairings = new java.util.ArrayList<>();
        for (BeanProperties.Property targetProperty : targetProperties.values()) {
            if (!targetProperty.isWritable()) {
                continue;
            }
            BeanProperties.Property sourceProperty = sourceProperties.get(targetProperty.name());
            if (sourceProperty == null || !sourceProperty.isReadable()) {
                continue;
            }
            Class<?> from = sourceProperty.getter().getReturnType();
            Class<?> to = targetProperty.setter().getParameterTypes()[0];
            if (!useConverter && !to.isAssignableFrom(from)) {
                // Assignability, not identity, matching CGLib: a String source feeds a
                // CharSequence setter as-is. isAssignableFrom is exact for primitives, so an int
                // getter still does not feed a long setter — that needs the converter.
                continue;
            }
            pairings.add(new Pairing(sourceProperty.getter(), targetProperty.setter()));
        }

        ClassDefiner definer = ClassDefiner.alongside(target);
        DefinedClass defined = definer.define(emit(
                definer.generatedNameFor(target, "$$Copier"), source, target, pairings,
                useConverter));

        BeanCopier copier = (BeanCopier) Instantiator.register(defined).newInstance();
        copier.mapping = describe(source, target, pairings);
        INSTANCES.get(defined.type()).compareAndSet(null, copier);
        return defined.type();
    }

    private record Pairing(Method getter, Method setter) {
    }

    /**
     * Copies every matched property.
     *
     * @param source    the bean to read from; must be an instance of the source class
     * @param target    the bean to write to; must be an instance of the target class
     * @param converter applied to every value, or {@code null} if the copier was created without
     *                  one
     */
    public abstract void copy(Object source, Object target, Converter converter);

    /**
     * Which properties this copier will move, and which it will not.
     *
     * <p>Silently skipping an unmatched property is CGLib's behaviour and is usually what you want,
     * but "why did that field not copy" is a question worth being able to answer.
     *
     * @return a readable description of the mapping
     */
    public String describeMapping() {
        return mapping;
    }

    private static String describe(Class<?> source, Class<?> target, List<Pairing> pairings) {
        StringBuilder description = new StringBuilder(source.getSimpleName())
                .append(" -> ").append(target.getSimpleName()).append(": ");
        if (pairings.isEmpty()) {
            return description.append("no properties matched").toString();
        }
        for (Pairing pairing : pairings) {
            description.append(pairing.getter().getName()).append("/")
                    .append(pairing.setter().getName()).append(' ');
        }
        return description.toString().trim();
    }

    /**
     * Generates the copier.
     *
     * <p>Two shapes, chosen once rather than branched at run time. Without a converter each
     * property is a read immediately followed by a write, with no boxing at all for primitives.
     * With one, the value is boxed, passed through {@link Converter#convert}, and cast or unboxed
     * on the way into the setter.
     */
    private static byte[] emit(String self, Class<?> source, Class<?> target,
                               List<Pairing> pairings, boolean useConverter) {
        CwMethodType copySignature = CwMethodType.of(CwType.VOID, CwType.OBJECT, CwType.OBJECT,
                CwType.objectType(internal(Converter.class)));

        CwClassWriter writer = CwClassWriter
                .of(AccessFlags.PUBLIC | AccessFlags.SUPER, self, internal(BeanCopier.class))
                .sourceFile(target.getSimpleName() + "$$Copier.java");

        writer.constructor(AccessFlags.PUBLIC, CwMethodType.of(CwType.VOID))
                .code()
                .loadThis()
                .invokeConstructor(internal(BeanCopier.class), CwMethodType.of(CwType.VOID))
                .returnValue();

        CodeBuilder code = writer.method(AccessFlags.PUBLIC, "copy", copySignature).code();

        int sourceSlot = code.declareLocal(CwType.of(source));
        int targetSlot = code.declareLocal(CwType.of(target));
        code.loadArgument(0).checkCast(CwType.of(source)).store(sourceSlot, CwType.of(source));
        code.loadArgument(1).checkCast(CwType.of(target)).store(targetSlot, CwType.of(target));

        for (Pairing pairing : pairings) {
            Class<?> valueType = pairing.getter().getReturnType();
            Class<?> setterType = pairing.setter().getParameterTypes()[0];

            code.load(targetSlot, CwType.of(target));
            if (useConverter) {
                // The converter is the receiver of the interface call below, so it has to go on
                // the stack before its arguments -- beneath the value, above the target.
                code.loadArgument(2);
            }
            code.load(sourceSlot, CwType.of(source));
            invoke(code, source, pairing.getter());

            if (useConverter) {
                code.box(CwType.of(valueType));
                code.pushClassConstant(CwType.of(setterType));
                code.pushString(pairing.setter().getName());
                code.invokeInterface(internal(Converter.class), "convert",
                        CwMethodType.of(CwType.OBJECT, CwType.OBJECT, CwType.CLASS,
                                CwType.OBJECT));
                // Null becomes the zero value for a primitive setter, matching how a proxy handles
                // a null from a callback.
                code.unboxOrDefault(CwType.of(setterType));
            }
            invoke(code, target, pairing.setter());
        }
        code.returnValue();

        return writer.toByteArray();
    }

    private static void invoke(CodeBuilder code, Class<?> owner, Method method) {
        CwMethodType signature = CwMethodType.of(method);
        if (owner.isInterface()) {
            code.invokeInterface(internal(owner), method.getName(), signature);
        } else {
            code.invokeVirtual(internal(owner), method.getName(), signature);
        }
    }

    private static String internal(Class<?> type) {
        return type.getName().replace('.', '/');
    }
}
