package com.classwright.beans;

import com.classwright.ClasswrightException;
import com.classwright.core.AccessFlags;
import com.classwright.core.CodeBuilder;
import com.classwright.core.CwClassWriter;
import com.classwright.core.CwMethodType;
import com.classwright.core.CwType;
import com.classwright.runtime.ClassDefiner;
import com.classwright.runtime.DefinedClass;
import com.classwright.runtime.GenerationCache;
import com.classwright.runtime.Instantiator;

import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.List;

/**
 * Reads or writes a chosen set of a bean's properties in one call.
 *
 * <pre>{@code
 * BulkBean bulk = BulkBean.create(Order.class,
 *         new String[]{"getId", "getTotal"},
 *         new String[]{"setId", "setTotal"},
 *         new Class<?>[]{String.class, int.class});
 *
 * Object[] values = bulk.getPropertyValues(order);
 * bulk.setPropertyValues(otherOrder, values);
 * }</pre>
 *
 * <p>Where {@link BeanCopier} moves values between two beans, this moves them between a bean and an
 * {@code Object[]} — which is what serialisation, persistence, and row mapping actually need. The
 * accessors are resolved once and the generated methods are a straight sequence of direct calls.
 *
 * <p>The three arrays are positional and must be the same length. A {@code null} entry in either
 * name array means that position is skipped in that direction, which is how a read-only or
 * write-only property is expressed.
 */
public abstract class BulkBean {

    private String[] getterNames;
    private String[] setterNames;
    private Class<?>[] propertyTypes;

    /**
     * For generated subclasses. Use {@link #create} to obtain an instance.
     */
    protected BulkBean() {
    }

    /**
     * Creates a bulk accessor.
     *
     * @param beanClass     the bean type
     * @param getterNames   the read accessors, in order; entries may be {@code null}
     * @param setterNames   the write accessors, in the same order; entries may be {@code null}
     * @param propertyTypes the property types, in the same order
     * @return the accessor
     */
    public static BulkBean create(Class<?> beanClass, String[] getterNames, String[] setterNames,
                                  Class<?>[] propertyTypes) {
        if (beanClass == null || getterNames == null || setterNames == null
                || propertyTypes == null) {
            throw new ClasswrightException("all four arguments are required");
        }
        if (getterNames.length != setterNames.length
                || getterNames.length != propertyTypes.length) {
            throw new ClasswrightException("the three arrays are positional and must be the same "
                    + "length, but got " + getterNames.length + " getters, " + setterNames.length
                    + " setters, and " + propertyTypes.length + " types");
        }

        // Cloned before keying: the key must not change under the cache if the caller reuses and
        // mutates the arrays.
        String[] getterCopy = getterNames.clone();
        String[] setterCopy = setterNames.clone();
        Class<?>[] typeCopy = propertyTypes.clone();
        BulkKey key = new BulkKey(getterCopy, setterCopy, typeCopy);

        // Accessor resolution and generation run only on a miss; CGLib cached these classes, and
        // per-call regeneration is a thousandfold slowdown for the serialisation-style loops this
        // class exists to serve.
        Class<?> generated = GenerationCache.computeIfAbsent(beanClass, key,
                () -> defineBulk(beanClass, getterCopy, setterCopy, typeCopy));

        BulkBean bulk = (BulkBean) Instantiator.forGenerated(generated).newInstance();
        bulk.getterNames = getterCopy;
        bulk.setterNames = setterCopy;
        bulk.propertyTypes = typeCopy;
        return bulk;
    }

    /**
     * The generation-cache key: positional accessor names and types. One class, two lives, the
     * same pattern as {@code Enhancer}'s key.
     *
     * <p>As a <em>probe</em> — what every {@code create()} builds — it aliases the cloned arrays
     * and holds the property types strongly; it exists for one lookup and allocates nothing
     * beyond itself. As a <em>stored key</em>, built by {@link #retained()} only on a miss, the
     * property types become weak. The rule being honoured is the cache-wide one: the entry is
     * anchored on the bean class, and a key must not strongly retain some <em>other</em> class —
     * a property type from a disposable loader, say — for the anchor's lifetime. The sharpest
     * case is a skipped slot ({@code null} accessor names): the type is still part of the
     * positional identity, but the generated bytecode never references it, so the key was the
     * only thing pinning it. A stored key whose referent is gone can never match again and
     * reports itself stale; accessor <em>names</em> stay strong in both forms — strings pin no
     * loader.
     */
    private static final class BulkKey
            implements GenerationCache.StaleKey, GenerationCache.ProbeKey {

        private final String[] getters;
        private final String[] setters;

        /** {@code Class<?>} elements in a probe; {@code WeakReference<Class<?>>} once stored. */
        private final Object[] types;

        private final boolean weak;
        private final int hash;

        /** The probe form: strong parts, no allocation beyond this object. */
        BulkKey(String[] getters, String[] setters, Class<?>[] types) {
            this.getters = getters;
            this.setters = setters;
            this.types = types;
            this.weak = false;

            // Manual, collection-stable hashing: class NAME hashes, so the stored twin hashes
            // identically even after a referent is collected.
            int h = Arrays.hashCode(getters);
            h = 31 * h + Arrays.hashCode(setters);
            for (Class<?> type : types) {
                h = 31 * h + type.getName().hashCode();
            }
            this.hash = h;
        }

        /** The stored form; only {@link #retained()} calls this. */
        private BulkKey(BulkKey probe) {
            this.getters = probe.getters;
            this.setters = probe.setters;
            Object[] weakTypes = new Object[probe.types.length];
            for (int i = 0; i < weakTypes.length; i++) {
                weakTypes[i] = new java.lang.ref.WeakReference<>(probe.types[i]);
            }
            this.types = weakTypes;
            this.weak = true;
            this.hash = probe.hash;
        }

        @Override
        public Object retained() {
            return weak ? this : new BulkKey(this);
        }

        private Class<?> typeAt(int index) {
            Object part = types[index];
            return (Class<?>) (part instanceof java.lang.ref.WeakReference<?> reference
                    ? reference.get() : part);
        }

        @Override
        public boolean isStale() {
            if (!weak) {
                return false;           // a probe is never stored, so it is never stale
            }
            for (int i = 0; i < types.length; i++) {
                if (typeAt(i) == null) {
                    return true;
                }
            }
            return false;
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) {
                return true;
            }
            if (!(other instanceof BulkKey that) || hash != that.hash
                    || types.length != that.types.length
                    || !Arrays.equals(getters, that.getters)
                    || !Arrays.equals(setters, that.setters)) {
                return false;
            }
            for (int i = 0; i < types.length; i++) {
                Class<?> mine = typeAt(i);
                if (mine == null || mine != that.typeAt(i)) {
                    return false;       // a collected referent matches nothing, ever
                }
            }
            return true;
        }

        @Override
        public int hashCode() {
            return hash;
        }
    }

    private static Class<?> defineBulk(Class<?> beanClass, String[] getterNames,
                                       String[] setterNames, Class<?>[] propertyTypes) {
        Method[] getters = new Method[getterNames.length];
        Method[] setters = new Method[setterNames.length];
        for (int i = 0; i < getterNames.length; i++) {
            getters[i] = resolve(beanClass, getterNames[i], propertyTypes[i], true, i);
            setters[i] = resolve(beanClass, setterNames[i], propertyTypes[i], false, i);
        }

        ClassDefiner definer = ClassDefiner.alongside(beanClass);
        DefinedClass defined = definer.define(emit(
                definer.generatedNameFor(beanClass, "$$Bulk"), beanClass, getters, setters,
                propertyTypes));
        Instantiator.register(defined);
        return defined.type();
    }

    private static Method resolve(Class<?> beanClass, String name, Class<?> propertyType,
                                  boolean isGetter, int position) {
        if (name == null) {
            return null;
        }
        try {
            return isGetter
                    ? beanClass.getMethod(name)
                    : beanClass.getMethod(name, propertyType);
        } catch (NoSuchMethodException e) {
            // Structured, not just worded: the failing position travels as data so the CGLib
            // compatibility layer can reproduce BulkBeanException(index) without parsing text.
            BulkAccessException failure = new BulkAccessException(beanClass.getName()
                    + " has no public method " + name
                    + (isGetter ? "()" : "(" + propertyType.getSimpleName() + ")")
                    + ", named at position " + position, position);
            failure.initCause(e);
            throw failure;
        }
    }

    /**
     * Reads the properties into the supplied array.
     *
     * <p>Failures propagate raw — a getter's own exception, an
     * {@link ArrayIndexOutOfBoundsException} for an undersized {@code values} array. Reads have
     * no partial-write state worth pointing at, so no wrapping is added; the write side below
     * differs, deliberately.
     *
     * @param bean   the bean to read
     * @param values an array at least as long as the property list; primitives arrive boxed
     */
    public abstract void getPropertyValues(Object bean, Object[] values);

    /**
     * Writes the properties from the supplied array.
     *
     * <p>Anything a property write throws — the setter's own exception, a value of the wrong
     * type, {@code null} for a primitive property, an undersized {@code values} array — arrives
     * wrapped in a {@link BulkAccessException} carrying the failing position, because earlier
     * positions have already been written and the position is what makes that diagnosable.
     *
     * @param bean   the bean to write
     * @param values the values, boxed for primitives; {@code null} is an error for a primitive
     *               property
     */
    public abstract void setPropertyValues(Object bean, Object[] values);

    /**
     * Reads the properties into a fresh array.
     *
     * @param bean the bean to read
     * @return the values, in property order
     */
    public Object[] getPropertyValues(Object bean) {
        Object[] values = new Object[propertyTypes.length];
        getPropertyValues(bean, values);
        return values;
    }

    /**
     * The property types, in order.
     *
     * @return the property types, in index order
     */
    public Class<?>[] getPropertyTypes() {
        return propertyTypes.clone();
    }

    /**
     * The read accessor names, in order.
     *
     * @return the getter method names, in index order
     */
    public String[] getGetters() {
        return getterNames.clone();
    }

    /**
     * The write accessor names, in order.
     *
     * @return the setter method names, in index order
     */
    public String[] getSetters() {
        return setterNames.clone();
    }

    @Override
    public String toString() {
        return "BulkBean" + Arrays.toString(propertyTypes);
    }

    private static byte[] emit(String self, Class<?> beanClass, Method[] getters, Method[] setters,
                               Class<?>[] propertyTypes) {
        CwMethodType signature = CwMethodType.of(CwType.VOID, CwType.OBJECT, CwType.OBJECT_ARRAY);

        CwClassWriter writer = CwClassWriter
                .of(AccessFlags.PUBLIC | AccessFlags.SUPER, self, internal(BulkBean.class))
                .sourceFile(beanClass.getSimpleName() + "$$Bulk.java");

        writer.constructor(AccessFlags.PUBLIC, CwMethodType.of(CwType.VOID))
                .code()
                .loadThis()
                .invokeConstructor(internal(BulkBean.class), CwMethodType.of(CwType.VOID))
                .returnValue();

        emitGetters(writer, beanClass, getters, signature);
        emitSetters(writer, beanClass, setters, propertyTypes, signature);
        return writer.toByteArray();
    }

    private static void emitGetters(CwClassWriter writer, Class<?> beanClass, Method[] getters,
                                    CwMethodType signature) {
        CodeBuilder code = writer
                .method(AccessFlags.PUBLIC, "getPropertyValues", signature)
                .code();
        int beanSlot = code.declareLocal(CwType.of(beanClass));
        code.loadArgument(0).checkCast(CwType.of(beanClass)).store(beanSlot, CwType.of(beanClass));

        // Deliberately no indexed wrapping here, asymmetric with the setter side below: CGLib
        // wrapped only setter failures, and a getter's own exception (or an undersized
        // destination array) propagated raw. Reads have no partial-write state worth pointing
        // at, so the raw exception loses nothing — and the getter path stays free of
        // exception-table machinery.
        for (int i = 0; i < getters.length; i++) {
            if (getters[i] == null) {
                continue;
            }
            code.loadArgument(1).pushInt(i);
            code.load(beanSlot, CwType.of(beanClass));
            invoke(code, beanClass, getters[i]);
            code.box(CwType.of(getters[i].getReturnType()));
            code.arrayStore(CwType.OBJECT);
        }
        code.returnValue();
    }

    private static void emitSetters(CwClassWriter writer, Class<?> beanClass, Method[] setters,
                                    Class<?>[] propertyTypes, CwMethodType signature) {
        CodeBuilder code = writer
                .method(AccessFlags.PUBLIC, "setPropertyValues", signature)
                .code();
        int beanSlot = code.declareLocal(CwType.of(beanClass));
        code.loadArgument(0).checkCast(CwType.of(beanClass)).store(beanSlot, CwType.of(beanClass));

        // The position travels in a local, stored before each property block, so the catch can
        // wrap whatever escapes with the index that failed. The store costs one instruction per
        // property; the exception table is inert until something throws — the same price CGLib's
        // generated code paid for its BulkBeanException contract.
        int indexSlot = code.declareLocal(CwType.INT);
        code.pushInt(0).store(indexSlot, CwType.INT);
        code.tryCatch(
                () -> {
                    for (int i = 0; i < setters.length; i++) {
                        if (setters[i] == null) {
                            continue;
                        }
                        code.pushInt(i).store(indexSlot, CwType.INT);
                        code.load(beanSlot, CwType.of(beanClass));
                        code.loadArgument(1).pushInt(i).arrayLoad(CwType.OBJECT);
                        // Strict unbox: null for a primitive property is a caller error and must
                        // fail (as an NPE, wrapped with the index), not silently write zero.
                        // CGLib behaved so, and silent zeroing hides real bugs either way.
                        code.unbox(CwType.of(propertyTypes[i]));
                        invoke(code, beanClass, setters[i]);
                    }
                    code.returnValue();
                },
                CwType.THROWABLE,
                () -> emitWrapIndexed(code, indexSlot));
    }

    /** The catch handler: wrap the caught throwable and the failing index, and rethrow. */
    private static void emitWrapIndexed(CodeBuilder code, int indexSlot) {
        int caught = code.declareLocal(CwType.THROWABLE);
        code.store(caught, CwType.THROWABLE);
        code.newInstance(CwType.of(BulkAccessException.class))
                .dup()
                .load(caught, CwType.THROWABLE)
                .load(indexSlot, CwType.INT)
                .invokeConstructor(internal(BulkAccessException.class),
                        CwMethodType.of(CwType.VOID, CwType.THROWABLE, CwType.INT))
                .throwException();
    }

    private static void invoke(CodeBuilder code, Class<?> owner, Method method) {
        CwMethodType signature = CwMethodType.of(method);
        if (owner.isInterface()) {
            code.invokeInterface(internal(owner), method.getName(), signature);
        } else {
            code.invokeVirtual(internal(owner), method.getName(), signature);
        }
    }

    private static String internal(Class<?> type) {
        return type.getName().replace('.', '/');
    }
}
